# name of your github action
name: CI
on:
  push:
    branches:
    # this will run on the electron branch
      - master
jobs:
  build_on_mac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: installes dependencies
      run: npm install
    - name: build
      run: npm run make
      
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: installes dependencies
      run: npm install
    - name: build
      run: npm run make
