# name of your github action
name: CI# this will help you specify where to run 
on:
  push:
    branches:
    # this will run on the electron branch
      - master
jobs:
  build_on_mac:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: see directory
      run: ls
      
  build_on_win:
    runs-on: windows-2016
    steps:
    - uses: actions/checkout@v2       
    - uses: actions/setup-node@master
      with:
        node-version: 12
    - name: see directory
      run: ls
